# Copyright (c) 2022 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the MIT license, see file LICENSE.txt

name: Run the Test Suite

on:
  pull_request:
  push:
  schedule:
    - cron: '0 16 * * 5'  # Every Friday 4pm
  workflow_dispatch:

jobs:
  run_test_suite:
    strategy:
      matrix:
        python-version: [3.9, 3.13]  # no current need for in-between versions
    name: Run the Test Suite
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # v5.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run the Test Suite
        run: |-
          set -x
          pip install -U setuptools  # for Python >=3.12
          pip install pytest
          python setup.py sdist
          cd dist/
          tar xf hsluv-*.tar.gz
          cd hsluv-*/
          pytest -v tests/
